MvcCrudDepartamentos/Models/Departamento.cs
namespace MvcCrudDepartamentos.Models
{
    public class Departamento
    {
        public int IdDepartamento { get; set; }
        public string Nombre { get; set; }
        public string Localidad { get; set; }
    }
}

MvcCrudDepartamentos/Models/ErrorViewModel.cs
namespace MvcCrudDepartamentos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCrudDepartamentos/Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCrudDepartamentos.Models;
using MvcCrudDepartamentos.Repositories;

namespace MvcCrudDepartamentos.Controllers
{
    public class DepartamentosController : Controller
    {
        RepositoryDepartamentos repo;

        public DepartamentosController(RepositoryDepartamentos repo)
        {
            this.repo = repo;
        }

        //AQUI MOSTRAMOS TODOS LOS DEPARTAMENTOS
        public IActionResult Index()
        {
            List<Departamento> departamentos = this.repo.GetDepartamentos();
            return View(departamentos);
        }

        public IActionResult Create()
        {
            return View();
        }
        //VAMOS A RECIBIR TODO EL OBJETO DEPARTAMENTO
        //TENEMOS DOS OPCIONES:
        //1) RECIBIMOS TODO EL OBJETO
        //2) RECIBIMOS CADA VARIABLE
        [HttpPost]
        public IActionResult Create(Departamento dept)
        {
            this.repo.InsertDepartamento(dept.IdDepartamento, dept.Nombre, dept.Localidad);
            //EN LUGAR DE MOSTRAR UN MENSAJE O ALGO, LO QUE VAMOS A REALIZAR
            //ES VOLVER A LA VISTA DONDE ESTAN TODOS LOS DEPARTAMENTOS (Index)
            return RedirectToAction("Index");
        }
        //AL EDITAR, VAMOS A RECIBIR UN ID DEL DEPARTAMENTO
        //LO QUE HAREMOS SERA BUSCAR EL DEPARTAMENTO POR SU ID
        //Y LO ENVIAREMOS A LA VISTA PARA MOSTRAR SUS DATOS 
        //EN LAS CAJAS
        public IActionResult Edit(int iddepartamento)
        {
            Departamento dept = this.repo.FindDepartamento(iddepartamento);
            return View(dept);
        }
        [HttpPost]
        public IActionResult Edit(Departamento dept)
        {
            this.repo.UpdateDepartamento(dept.IdDepartamento, dept.Nombre, dept.Localidad);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int iddepartamento)
        {
            this.repo.DeleteDepartamento(iddepartamento);
            return RedirectToAction("Index");
        }
    }
}
    

MvcCrudDepartamentos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCrudDepartamentos.Models;
using System.Diagnostics;

namespace MvcCrudDepartamentos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCrudDepartamentos/Views/Departamentos/Create.cshtml
@model MvcCrudDepartamentos.Models.Departamento

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdDepartamento" class="control-label"></label>
                <input asp-for="IdDepartamento" class="form-control" />
                <span asp-validation-for="IdDepartamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localidad" class="control-label"></label>
                <input asp-for="Localidad" class="form-control" />
                <span asp-validation-for="Localidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcCrudDepartamentos/Views/Departamentos/Edit.cshtml
@model MvcCrudDepartamentos.Models.Departamento

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdDepartamento" class="control-label"></label>
                <input asp-for="IdDepartamento" class="form-control" />
                <span asp-validation-for="IdDepartamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localidad" class="control-label"></label>
                <input asp-for="Localidad" class="form-control" />
                <span asp-validation-for="Localidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcCrudDepartamentos/Views/Departamentos/Index.cshtml
@model IEnumerable<MvcCrudDepartamentos.Models.Departamento>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista Departamentos12</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdDepartamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Localidad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdDepartamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Localidad)
            </td>
            <td>
                <a asp-controller="Departamentos"
                    asp-action="Edit"
                    asp-route-iddepartamento="@item.IdDepartamento"
                    class="btn btn-outline-info">
                    Editar
                </a>
                <a asp-controller="Departamentos"
                 asp-action="Delete"
                 asp-route-iddepartamento="@item.IdDepartamento"
                 class="btn btn-outline-danger">
                    Delete
                </a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcCrudDepartamentos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCrudDepartamentos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCrudDepartamentos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCrudDepartamentos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCrudDepartamentos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Departamentos"
                               asp-action="Index"
                               class="nav-link text-dark">
                                Departamentos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCrudDepartamentos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>